# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ca94e668d1004a7c760b2ebdefddaa7"
name = "test-omar-best-price"
handle = "test-omar-best-price"
application_url = "https://var-chat-tramadol-emperor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "omardev2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://var-chat-tramadol-emperor.trycloudflare.com/auth/callback",
  "https://var-chat-tramadol-emperor.trycloudflare.com/auth/shopify/callback",
  "https://var-chat-tramadol-emperor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
