# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "67725bc263c7bfe0e51e89cc030025c0"
name = "the-30-days-best-price"
handle = "the-30-days-best-price-1"
application_url = "https://eng-cool-unusual-last.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yousef-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://eng-cool-unusual-last.trycloudflare.com/auth/callback",
  "https://eng-cool-unusual-last.trycloudflare.com/auth/shopify/callback",
  "https://eng-cool-unusual-last.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
